# 添加数据源及数据连接池类型
spring:
  datasource:
    url: jdbc:mysql://rm-bp17rs6x3634h47kkdo.mysql.rds.aliyuncs.com:3306/jssdMySql
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: lab_286338407
    password: 75062e1cf53c_#@Aa

# 日志级别更改
logging:
  level:
    root: info
    pers.jssd.elegenceservice.service: debug
